# Generated by Django 4.0.4 on 2022-05-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_custom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom',
        ),
    ]
